
1+2*3/4-(5+6)+7

if(i<1) {
    println("A");1
} elif (i==2) {
    2
} else {
    3
}


a.x.y.z=5


while i<5 {

}

if i<5 {

} elif i==6 {

} else {

}

if if 1<2 {} else {} {}

if (if 1<2 {} else {}) {}





for x in 0 .. 4 {

}

//for x in 0 to 4 {}

for (x in 2 .. 5) {

}
while i<5 {

}

while (j<15) {

}

if i<5 {

} elif i==6 {

} else {

}

if if 1<2 {} else {} {}

if (if (1<2) {} else {}) {}

if 1