var i=5,j=6;

fn myfunc(a,b,c) {
    return a+b*c
}

if (i < 5) {

} elif (j>5) {

} else {

} var q = 77 var x=9;

myfunc(1,2,if (i<2) {3} else {4}+ 123)


myfunc(var i=4,j=5;,for(var i=4;i<40;i++){i},a=5)

var i=b=4;
a=b=3

/*
stmts
* var
* set

expr
* if
*

todo
* for expr, need to delay builder calls
* how to handle and/or/add/sub/mul/div/neg/etc cmds?
** have separate cmd_scope.add's
** when expr parser rearranges things, need to provide that as input
*** could have expr parser generate its own parsed primitives etc

* have arrays eg [1,2,3]
* have dicts eg {a:1,b:2}
** can't have ternaries? eg "a?1:2" because of ":"

** how to differentiate between code blocks and dicts?
** how to tell difference between code block and empty dict? eg "var a = {}" and "var a = {1}"

* don't allow code blocks to be used within expr? eg func({var a=5; a})

* if
** to be an expr, needs else, or could have it return nil on failure
** if statements need to use "()/{}" for bodies?
*** otherwise how to tell dif between body and expr
**** eg "if 1 < if i>3 4 else 5 6" vs "if (1<if (i>3) {4} else {5}) {6}"
**** eg "if (1 < 2) 1+if(b) 4 else 5 else 6" vs "if (1<2) {1+if(b){4}else{5}} else {6}"

* code blocks can't be used as expr, except when used in if expr, they also return void

* don't allow variables to be used as statement? eg "{a:1}" 123
*/

func({}, if(1<3){}else{})

func({var a=4;a+1})

if (1 < if (i>3) {4} else {5}) {
    6
}

if (1 < {if (i>3) {4} else {5}}) {
    6
}

if (1<2) {1+if(b){4}else{5}} else {6}

var d={a:1,b:2}
var d=[1,2,3] var a

if(a) {} if(b){}
if(a) {}; if(b){}

var a = [a:2,b:3]
var a = [1,a:2,b:3]
var a = fn(a) {return a+1}

e.add_event_listener("aaa", fn(){

})

{var i=1}+5
{var i=1;i}+5

if if i>5 {true}else{false} {1} {2}
